
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apii
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
application:
  security:
    jwt:
      secret-key: 294A404E635266556A586E327235753878214125442A472D4B6150645367566B
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
